CREATE TABLE IF NOT EXISTS `User` (
	`user` INT NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(40) NOT NULL,
	`name` VARCHAR(40) NULL,
	`username` VARCHAR(40) NULL,
	`isAnonymous` BOOLEAN NOT NULL DEFAULT 0,
	`about` TEXT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Forum` (
	`forum` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(40) NOT NULL,
	`short_name` VARCHAR(40) NOT NULL,
	`user` VARCHAR(40) NOT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Thread` (
	`thread` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(40) NOT NULL,
	`user` VARCHAR(4) NOT NULL,
	`message` TEXT NOT NULL,
	`forum` VARCHAR(40) NOT NULL,
	`isDeleted` BOOLEAN NOT NULL DEFAULT 0,
	`isClosed` BOOLEAN NOT NULL DEFAULT 0,
	`date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`slug` VARCHAR(40) NOT NULL,
	`likes` INT NOT NULL DEFAULT 0,
	`dislikes` INT NOT NULL DEFAULT 0,
	`points` INT NOT NULL DEFAULT 0,
	`posts` INT NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `Post` (
	`post` INT NOT NULL AUTO_INCREMENT,
	`user` VARCHAR(40) NOT NULL,
	`thread` INT NOT NULL,
	`forum` VARCHAR(40) NOT NULL,
	`message` TEXT NOT NULL,
	`parent` INT NULL DEFAULT NULL,
	`date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`likes` INT NOT NULL DEFAULT 0,
	`dislikes` INT NOT NULL DEFAULT 0,
	`points` INT NOT NULL DEFAULT 0,
	`isSpam` BOOLEAN NOT NULL DEFAULT 0,
	`isEdited` BOOLEAN NOT NULL DEFAULT 0,
	`isDeleted` BOOLEAN NOT NULL DEFAULT 0,
	`isHighlighted` BOOLEAN NOT NULL DEFAULT 0,
	`isApproved` BOOLEAN NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8;

